spring:
  application:
    name: ORDER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      dafultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost